# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

# KDE jobs
include:
  - project: sysadmin/ci-utilities
    rules:
    - if: $CI_SERVER_HOST =~ /kde\.org$/
    file:
      - /gitlab-templates/linux.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml

# Gitlab jobs
mingw-win32-build:
  stage: build
  image: maxrd2/arch-mingw
  only:
    - /^obs/.*/
    - $CI_SERVER_HOST =~ /gitlab\.com$/
  script:
    - |-
      git="git -C $CI_PROJECT_DIR"
      $git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
      $git fetch origin --depth=200
      gitver="$($git describe --always --tags --abbrev=10 "${CI_COMMIT_SHA}")"
      echo "SubtitleComposer $gitver" > $CI_PROJECT_DIR/version.txt
    - pkg/mingw/build.sh
    # gitlab artifact paths are relative to CI_PROJECT_DIR
    - mv /home/devel/build/SubtitleComposerSetup.exe $CI_PROJECT_DIR
  artifacts:
    paths:
      - SubtitleComposerSetup.exe
      - version.txt
