image: maxrd2/arch-mingw

mingw-win32-build:
  stage: build
  only:
    - /^obs/.*/
  script:
    #- git="git -C $CI_PROJECT_DIR"
    #- $git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
    #- $git fetch origin --depth=200
    #- gitver="$($git describe --always --tags --abbrev=10 "$($git log --reverse --oneline --no-abbrev-commit origin/${CI_DEFAULT_BRANCH}..${CI_COMMIT_SHA} | head -n 1 | cut -d ' ' -f 1)^")"
    #- echo "Updating version to $gitver"
    #- sed -E "s|SUBTITLECOMPOSER_VERSION_STRING|\"${gitver#v}\"|" -i $CI_PROJECT_DIR/src/main.cpp
    - pkg/mingw/build.sh
  artifacts:
    paths:
      - build/SubtitleComposerSetup.exe
